---
submission_id: 480
categories: 'Session 3B'
title: Connecting floras and herbaria before 1850 – challenges and lessons learned in digital history of biodiversity
author:
  - name: Christian Forney
    orcid: 0000-0002-1318-4983
    email: christian.forney@unibe.ch
    affiliations:
      - University of Bern
  - name: Martin Stuber
    orcid: 0000-0001-9853-9570
    email: martin.stuber@unibe.ch
    affiliations:
      - University of Bern
keywords:
  - Biodiversity
  - Botanical networks
  - Digital edition
  - Digital herbaria
  - Digital humanities
  - FAIR data
  - History of botany
  - Knowledge history
abstract: |
  Floras and herbaria are particularly valuable sources both for historical analyses of the collaborative knowledge culture of botany and for research into historical biodiversity. Therefore, the digital representation of this complementary sources should fulfil the requirements of the humanities and natural sciences as well. In this paper, we describe challenges, solutions and lessons learned in this regard as a summary of experiences from multiple projects on the data and edition platform _hallerNet_ around the Bernese polymath Albrecht von Haller (1708–1777).
date: 08-08-2024
date-modified: 09-17-2024
bibliography: references.bib
---

## Introduction

To start with some definitions, the term “flora” – in the sense of a document – denotes a directory in which the plant species of a specific area are systematically listed, often together with a description and additional information. “Herbarium” refers to a collection of preserved (usually dried and pressed) plants or fungi for scientific purposes; an individual botanical object in a herbarium collected at a specific place and time is called a “specimen” [@Wagenitz2003].

## Floras and herbaria in the history of knowledge

Both the flora and the herbarium are regarded as decisive innovations in the development of botany into an independent scientific discipline from the mid-16th century onwards. Together with the botanical garden, which is functionally related and established in the same period [@Rieppel2016; @Findlen2006a], only the invention of the herbarium made it possible to work out regional floras based on systematic empirical fieldwork [@Flannery2023; @Müller-Wille2019]. Paula Findlen summarised the motivation behind this crucial invention: “The more naturalists observed nature in situ, the more they realized that limited contact with specimens did not yet yield enough knowledge to describe and compare medicinal herbs. They needed to take nature home” [@Findlen2006b, p. 447; see @Sunderland2016]. Findlen stands for the history of knowledge or the renewed history of science that firstly emphasises the shift from finalised knowledge to the act of its production, secondly shows an increased interest in the everyday intellectual life of small groups, circles or networks and thirdly focuses on practices and material cultures of knowledge [@Müller-WilleEtAl2017; @FörschlerMariss2017; @HolensteinSteinkeStuber2013]. In this perspective and with the catchy phrase “collecting as knowledge”, the creation of a natural history collection, such as a herbarium, is seen as knowledge production [@HeesenSpary2001]. The activity of collecting expresses not only the fact that dispersed natural objects are brought together in a single location, but also that the forms of representation associated with them, such as illustrations, descriptions, lists and publications, are included in the repositories, where they are available for comparison, retracing and synoptic synthesis [@Klemun2017, p. 235].

The precise structures and functions of floras and herbaria with their spatial relations between local and global can only be understood in the context of the “collaborative knowledge culture of botany”. Therefore the interplay of the three central resources on which botany depended in early modern times has to be reconstructed: living and dried plants, relevant specialised literature (e.g. floras) and correspondence [@Dietz2017a; @Dietz2017b]. The nexus of correspondence, plant transfer and collection policy was first reconstructed by Emma Spary using the example of the network of André Thouin (1747–1824), director of the _Jardin du Roi_ in Paris [@Spary2000, pp. 49-98]. The analysis of such networks draws attention to the extensive transfer of dried plants and seeds as the basis of knowledge production [@DauserEtAl2008]. A wide variety of methods has been used to correspond efficiently, to save time and to avoid loss of information. First and foremost is the use of reference catalogues. This means that lists of transmitted or desired plant species could simply be referred to the numbers that had been assigned to the species in an published flora [@Dietz2017a, pp. 96-99]. Secondly, network analyses show that natural history owes its existence not only to the outstanding figures, but also developed through the participation of thousands of amateurs working locally [@Klemun2017, p. 239]. Correspondence networks not only serve to improve understanding of herbaria and floras, it is also possible to go in the opposite direction: herbaria themselves can serve as a source for social network analyses by systematically evaluating the collectors of the individual specimen [@SiracusaEtAl2020; @GroomOReillyHumphrey2014].

## Digitisation of herbaria from a botanical perspective

The value of herbaria has long been recognized in the fields of taxonomy, systematics and biogeography. Moreover, in recent decades they have proven to be fundamental for dealing with the biology of climate change, biodiversity, phenology, conservation and biological invasions. Given the high scientific and cultural value of herbarium collections, many efforts to make them more accessible have already been made in the last 20 years. Digitization is an essential first step in the process of transforming this vast amount of data associated with physical specimen into flexible digital data formats that allow information to be re-categorized according to variable criteria [@Roma-Marzio2023, p. 108; see generally @AndraschkeWagner2020]. Building on centuries of research based on herbarium specimens collected over time and around the globe, which are freely accessible and aggregable, a “new era” of discovery, synthesis and prediction using digitized collection data is postulated [@JamesEtAl2018; @NelsonEllis2018]. Digitization and online availability of specimen facilitates the rapid exploration and dissemination of accurate biodiversity data on an unprecedented scale: “The emerging ‘herbarium of the future’ (or the ‘global metaherbarium’) will be the central element guiding the exploration, illumination, and prediction of plant biodiversity change in the Anthropocene” [@Davis2023, p. 412].
It should be borne in mind that collections are usually associated with various distortions that need to be characterised and mitigated to make data usable. Most common are taxonomic and collector biases, which can be understood as the effects of particular recording preferences of key collectors on the overall taxonomic composition of the biological collections to which they contribute [@SiracusaEtAl2020; @Davis2023, p. 421; @JaroszynskaEtAl2023]. In order to capture such phenomena so that they can be taken into account in the data analysis, precise knowledge of the entire context in which a herbarium was created is required. This is exactly the aim of the approach described above under history of knowledge. Obviously, there is a bridge here between the research interests of the natural sciences and the humanities.
An overview published in 2024 shows that the topic of accessibility and digitization of herbaria as “archives of biodiversity” has also gained new relevance in Switzerland in recent years. Apart from two major exceptions, the [_Platter-Herbarium_](https://www.burgerbib.ch/de/bestaende/privatarchive/einzelstuecke/platter-herbarium) and [_Les Herbiers de Rousseau_](https://lesherbiersderousseau.org/), there have been no attempts to do this in an interdisciplinary context [@Stämpfli2024]. Additionally there is a lack of including the interaction with the functionally linked correspondence networks and contemporary floras. For this reason, the experience with historical plants gained on _hallerNet_, on which we pursued an interdisciplinary approach to the interaction between different types of entities (letters, species, specimens, reviews), may be of general interest.

## Historical plants on the data and edition platform _hallerNet_

The data and edition platform [_hallerNet_](https://hallernet.org/) opens up historical networks of knowledge in Switzerland in their interconnectedness. The platform is institutionally supported by the _Albrecht von Haller Foundation of the Burgergemeinde Bern_ and the Historical Institute and the Institute for the History of Medicine at the University of Bern. The basis of the currently around 128,000 data objects is formed by extensive prosopographical and bibliographical data that has been compiled in a relational database (FAUST) since the early 1990s as part of three SNSF projects at the University of Bern. A transformation project (2016–2019) transferred this extensively interlinked data into a XML data structure compliant to the [_Text Encoding Initiative (TEI)_](https://tei-c.org/) and thus turned it into “reusable research data” based on the [_FAIR_](https://www.go-fair.org/fair-principles/) data criteria [@DängeliStuber2020]. The platform nowadays contains, among others, around 46,000 publications, 31,000 persons and 1,200 institutions, which are systematically linked to 9,000 edited reviews and 5,000 edited letters. In our context, the 4,955 plant entities currently on _hallerNet_ are at the centre. Starting point were the 1,737 species of flowering plants mentioned in Haller's Swiss Flora _Historia Stirpium_ [@Haller1768], which were systematically referenced in the aforementioned relational database to Haller's first edition of the Swiss Flora _Enumeratio_ [@Haller1742], to Linné's _Species plantarum_ [@Linné1753] and to the current nomenclature. This concordance between Haller's and Linné's nomenclature, compiled by Luc Lienhard with reference to Johan Rudolf Suter's _Flora Helvetica_ [@Suter1802], not only makes Haller's Swiss flora accessible, but does also provide access to pre-Linnaean botany in general. On this basis, we transformed the botanical data, which was originally divided into four different data types, for the new XML structure into a generic data model based on today's plant entities ([_InfoFlora_](https://www.infoflora.ch/de/), [_Global Biodiversity Information Facility GBIF_](https://www.gbif.org/)), and treat their (historical) names as name variants. In this way, entities become flexibly adaptable for other historical floras that are partly or completely outside Haller's and Linné's nomenclature. At the same time, the data model structured according to today's nomenclature facilitates reference to current issues in historical ecology. The following summary of realized, initiated or planned expansions illustrates this double advantage.

* **Ecological data**: The diverse ecological information in Haller's _Historia_ on habitat, frequency, typical altitudinal range and specific localities is of far above-average quality for the 18th century [@Lienhard2005; @DrouinLienhard2008]. _hallerNet_ systematically records a total of 7,545 locality details, whereby the 1,920 different localities have been georeferenced for the most part as kilometre squares with their corner points and additionally linked to the neighbouring municipalities (‘populated places’) in order to appear in the _hallerNet_ place register. Haller's extraordinary data is thus available in a flexible structure whose exploration is only just beginning [@Lienhard2008; @Lienhard2000]. Historical biodiversity research, which is high on the agenda of environmental history [@GoethemZandem2019], has a wealth of source material at its disposal. Using appropriate methods of analysis, this will massively extend its temporal scope beyond the Swiss state of research [@JaroszynskaEtAl2023; @WangEtAl2023; @StöckliEtAl2012; @Lachat2010].

* **Collectors and correspondents**: Haller's _Historia_ also often includes the collector to whom Haller owes the information. These 109 people are all curated on _hallerNet_ and systematically referenced for each species (1,342 times in total). The network is to be further expanded by systematically labelling the plants mentioned in Haller's botanical correspondence, some of which has already been edited on _hallerNet_ and most of which are made accessible via the [_International Image Interoperability Framework (IIIF)_](https://iiif.io). How great the potential of the correspondence is, both for the reconstruction of the ‘knowledge culture’ and for the supplementation and specification of the location data, is demonstrated by some analyses already available [@Favre2021; @Hächler2008; @Lienhard2005].

* **Book references and reviews**: For his extensive information on the plant species of his Swiss flora, Haller also uses a vast amount of historical data from his predecessors. For example synonyms and place references, which have already been added to _hallerNet_. Together with the links to Hallers other botanical publications [@SteinkeProfos2004, pp. 186-195], to the numerous botanical publications in Hallers personal library [@Monti1983-1994, integrated in _hallerNet_] and to Hallers countless botanical reviews in the _Göttingische Gelehrten Anzeigen_, all of which are available in edited form on _hallerNet_, the integral process of botanical knowledge production could be precisely reconstructed [see @DietzSubm; @Lienhard2005; @DrouinLienhard2008].

* **Useful plants**: 656 species or varieties are listed in a total of eleven systematic catalogues in the context of the _Bernese Economic Society_, which was presided over by Haller. In this catalogues, the Latin-universal plant names were consistently linked to the dialectal-regional plant names. On _hallerNet_, 755 actions are linked to them, most of which obtained from the meetings of the _Economic Society_ [@StuberLienhard2007; @Stuber2008]. In addition, Haller's Swiss Flora contains information on the medicinal or economic use of more than a quarter of all the flowering plants. This reveals a wide range of interferences with medicine, agriculture, forestry and economy [@DauserStuberSubm; @Gerber-VisserStuber2019; @Stuber2018; @BoscaniStuber2017].

* **Herbaria**: The digitisation of Haller's herbaria is one of the  most intruding unfulfilled postulates in the study of Haller's botany and beyond. Haller's main herbarium, which after being sold by his heirs to Emperor Joseph II was first sent to Pavia and later to Paris by Napoleon, is now in the _Muséum National d'Histoire Naturelle_ and comprises more than 10,000 specimens in a total of 60 volumes (including 8 volumes of cryptogams) [@MargézAupicLamy2006; @Zoller1958a]; further there is a smaller herbarium by Haller in Göttingen [@Zoller1958b]. Due to the fact that the current location of Haller's herbaria is not in Switzerland, its digitization is not in scope of being supported by the ongoing [_SwissCollNet_](https://swisscollnet.scnat.ch) project, the national initiative for the digitization of natural history collections [@FrickStiegerScheidegger2019]. As part of _SwissCollNet_, however, the lichen herbarium of Jean-Frédéric Chaillet (1747–1839), which is kept in the _Neuchâtel herbarium_ (NEU), has now been edited on _hallerNet_ as sub-project _Lichens of the Enlightenment_ led by Jason Grant. This is consequent in terms of content, as Chaillet operated as a direct Swiss successor to Haller and referred to him wherever possible. At the same time, it represents a milestone for _hallerNet_, as the platform data structures for Herbaria could be developed. The centrepiece are the 943 lichen specimens, which firstly contain the transcribed original information on the label. Secondly, they are linked to the original scan via  [_IIIF_](https://iiif.io/api/image) and additionally with positional accuracy, as there are several specimens sticked on one herbarium page. Thirdly, they are assigned to the species entities, which point to authority data ([_GBIF_](https://www.gbif.org/), [_Index Fungorum_](https://www.indexfungorum.org), [_SwissLichens_](https://swisslichens.wsl.ch)). This species entities also contain the data from historical floras, in this case all from the manuscript flora by Chaillet and, where already listed, from Haller's _Historia_. The information from historical floras is often the decisive key to relate the objects in a herbarium to present-day taxonomic databases. The assignment of source terms to standardised data is thus presented transparently on the platform, which is particularly essential for a period in which botanical nomenclature is still very unstable. Additionally, the structure of the data follows [Darwin Core](https://dwc.tdwg.org/) standard which facilitates the connection to other systems such as the Neuchâtel Herbarium, the emerging _SwissCollNet_ database or the global [_Index Herbariorum_](https://sweetgum.nybg.org/science/ih/) [@VustEtAl].

* **Plant lists**: The connectivity of _hallerNet_ is also demonstrated by Meike Knittel's ongoing guest edition of plant lists in the circle of the Zurich botanist Johannes Gessner (1709–1790), the _Naturforschende Gesellschaft_ and the botanical garden, which document the actual exchange of seeds and list a total of 1,829 individual actions [see @Knittel].

## Conclusion

Reconstructing the whole interaction in which floras and herbaria interplayed, difficulties arise in integrating digital approaches to historical correspondence networks [e.g. @EdmondsonEdelstein2019] with digitization methods for floras and herbaria, which are located in different scientific disciplines. The challenge for the data and edition platform [_hallerNet_](https://hallernet.org/) is therefore to find interdisciplinary solutions. With tools, methods and workflows of the digital humanities, traceable relations between text, scans and structural data are determined in an innovative way. That allows to rely today's botanical authority data systematically to the historical information such as changing plant names, specimens, locality information and plant collectors. For the interoperability of the data, the orientation towards the [Darwin Core](https://dwc.tdwg.org/) standard is mandatory, for the sustainable editorial quality the [_TEI_](https://tei-c.org/) guidelines. Originally developed in the natural sciences, the [_FAIR data principles_](https://www.go-fair.org/fair-principles/) became a standard in the humanities (especially for _GLAM_ institutions), and thus serve as an overarching guideline; in particular, _FAIR_ guarantees the sustainable handling of data, which therefore remains 'reusable' for future generations of users because the traces of the normalization and flexibilization processes can be traced in detail. With this integration of different disciplinary standards and different types of sources, _hallerNet_ could become a dynamic and cross-collection instrument for the interdisciplinary research of historical plants and biodiversity in Switzerland in the period before 1850. The current transformation of _hallerNet_ into the national collaborative platform _République des Lettres_, which began running in 2024 with the support of the _Data Science Lab_ of the University of Bern, will further strengthen this potential.

## References

::: {#refs}
:::
