---
submission_id: 473
categories: 'Session 4A'
title: Digital Film Collection Literacy – Critical Research Interfaces for the “Encyclopaedia Cinematographica”
author:
  - name: Moritz Greiner-Petter
    orcid: 0009-0008-5533-5007
    email: moritz.greiner@unilu.ch
    affiliations:
      - University of Lucerne
  - name: Sarine Waltenspül
    orcid: 0000-0001-7977-2721
    email: sarine.waltenspuel@unilu.ch
    affiliations:
      - University of Lucerne
keywords:
  - film collection
  - interface
  - encyclopaedia
abstract: |
  For some time now, there has been a desire to elevate film to the status of a scholarly publication, and thus to recognise it as a research product in its own right. Never before has this dream seemed so concrete: analogue film collections are extensively digitized and made reliably referenceable via permanent links (DOIs). However, there is often a gap between the digital present of collections and their (analogue) history – such as in the case of the Encyclopaedia Cinematographica (EC). The EC was a large-scale project of exceptional duration and scope (1952–90), conducted by the Institute for Scientific Film in Göttingen (IWF). The EC was intended as an encyclopedia of movement processes, comprising more than 3000 films from biology, ethnology and the technical sciences. In 2010, the IWF was dissolved and the collection was transferred to the Technische Informationsbibliothek Hannover (TIB), where the majority of it was digitized, and certain sections were made accessible online. The challenging layering of media, histories, technologies and institutional agendas that the EC presents as a research object demands various “literacies”, but also specifically designed research tools. The SNSF-funded research project “Visualpedia” (2022–2026) is dedicated to the question of how to appropriately activate and research such a collection entangled in the logics of archival digitization and digital library organization. In addition to a historical reappraisal of the institution and collection, various interfaces are being developed within the project to activate the collection with regard to different research questions. As part of the group presentation, we would like to provide insights into the research project and the interfaces developed.
date: 08-13-2024
bibliography: references.bib
---

For some time now, there has been a desire to elevate film to the status of a scholarly publication, and thus recognize it as a research publication in its own right. Never before has this dream seemed so concrete: analog film collections are being extensively digitized and made reliably referenceable via permanent links.

A recent example of large-scale digital (online) publication of scientific films is the so-called AV portal of the Technische Informationsbibliothek Hannover (TIB), the German National Library of Science and Technology. Since 2004, the TIB has acted as a registration agency for digital object identifiers (DOI) for non-textual scientific objects such as data, software, videos, etc.^[Anonymous, “TIB vergibt millionsten Digital Object Identifier. Bibliothek ist zweiterfolgreichstes DataCite-Mitglied nach Registrierungszahlen,” in: Nachrichten Informationsdienst Wissenschaft, 20/4/2015, <https://nachrichten.idw-online.de/2015/04/20/tib-vergibt-millionsten-digital-object-identifier> (accessed 20/12/2023).] In 2020, it was named Library of the Year by the German Library Association for its “pioneering role in shaping digital change”.^[Frank Mentrup quoted after <https://www.bibliotheksverband.de/bibliothek-des-jahres#BibliothekdesJahres2020> (accessed 28/11/2023).] The video collection on the AV portal has grown exponentially over the last ten years, especially in terms of talks and lectures, which currently comprise 35,000 of 45,000 contributions and have click figures in the thousands. However, 4,800 of the films – and thus a tenth of the current TIB holdings – were published by the Institut für den wissenschaftlichen Film Göttingen (IWF). The IWF was founded in the 1950s and was a leading national and international institute in the production, distribution, collection and conception of scientific films. For its flagship project, the Encyclopaedia Cinematographica (EC), films were published from 1952 until the 1990s, and archived and distributed until the institute’s liquidation in 2011. The film, photo and text collections as well as the contracts with the authors/scientists/filmmakers were then transferred to the TIB.

More than two-thirds of the IWF’s films are now available online, 1,500 films are not, as they are subject to “licensing restrictions”. They can only be viewed after contacting the TIB. The most popular films – not only in the IWF inventory, but in the AV portal as a whole – are films about the sexual behavior of animals – bonobos, domestic donkeys or Camargue horses – with a click lead of tens of times over other topics. In addition to films, the AV portal also lists formal, technical and content-related metadata.

First of all, there is a gap between the rich digital present of the AV portal and the analog history of the IWF collection. For example, there is no information on the provenance of the collection on the AV portal. On the overview page of the holdings of the former IWF Wissen und Medien gGmbH, there is no mention of the National Socialist predecessor institution, the Reichsstelle für den Unterrichtsfilm (RfdU), later Reichsanstalt für Film und Bild in Wissenschaft und Unterricht (RWU). However, it is listed as the publisher of several hundred films. The overview of the IWF only mentions the amount of films, the ongoing clarification of rights, the transfer to the TIB in 2012 and information about accessibility.^[See <https://www.tib.eu/de/recherchieren-entdecken/sondersammlungen/iwf-medienbestand> (accessed 4/12/2023).] The impression that emerges is that what interests the TIB about the scientific films is the opportunity to take on a pioneering role in the digital transformation, but not the history of the films, of the collection and of the institutions. Second, although the digitization and accessibility of the film collection online is a crucial prerequisite for its study, library interfaces like the AV portal of the TIB not always provide the most suitable tools for research of such complex materials. In the online interface, the films can hardly be experienced as a cohesive collection, but rather as individual and itemized entries. Meaningful relations between films, e.g. whether they are part of a series of similar films, are not well represented in the data. Searching within the library catalog often tends to remain on the edges of results, making it difficult to gain a broader or more condensed view of the collection that would allow for relevant insights into its logics and structure.

Thus, researching large collections, especially film collections, is logistically and conceptually challenging, as well as technically, ethically, and legally demanding. The challenging layering of media, histories, technologies, and institutional agendas requires not only different “literacies” but also specifically designed research tools.

The SNSF-funded research project “Visualpedia. ‘Atlas Encyclopaedia Cinematographica’ and the Visual Science and Technology Studies” (2022–2026)^[See <https://www.unilu.ch/fakultaeten/ksf/institute/seminar-fuer-kulturwissenschaften-und-wissenschaftsforschung/wissenschaftsforschung/forschung/visualpedia-atlas-encyclopaedia-cinematographica-and-the-visual-science-and-technology-studies/> (accessed 13/8/2024).] is dedicated to the question of how such a collection, entangled in the logics of archival digitization and digital library organization, can be appropriately activated and researched. The project is guided by the question of how scholars can not only research *about* visual artifacts, but also research *with* them, which is based on Peter Galison’s Visual STS first and second order approach [@galison2014]. On a meta-level, “Visualpedia” is also an experiment in collaborative research practices. In addition to a historical reappraisal of the institution and the collection, the team is developing various custom browser-based digital interfaces to activate the collection and reconfigure it in ways that facilitate its study more appropriately. It is important to note that our goal is neither to create a “better library catalog” with a particular “end user” in mind, nor to provide a streamlined interface for the library that licenses the films, nor is it to speed up the digital transformation of film archives. Rather, our aim is to slow it down, or at least to make it a little more thoughtful and a little more difficult by acknowledging the historical, medial, ethical, and legal complexities that surround this collection.

The first interface developed in the project, titled “E-EC Explorer” (working title) provides an overview of the roughly 3000 EC films in the TIB library catalog, that so far has been missing for an extensive study of the collection. The interface is based on the publicly available data provided by TIB that we scraped from the website of the AV portal. Entries are arranged in a scalable grid and include metadata for each film, preview images if available, and links to the original entries in the library catalog. Films can be filtered by basic categories, like the thematic section of the collection, with more filters and sorting capabilities currently in development. This relatively straightforward visual reconfiguration of the collection already provides a much better sensibility for the structure and aesthetics of the film encyclopedia as a whole. The interface also indicates the accessibility and copyright status of each entry, thus implicitly generating a mapping of the digitization logics of TIB.

A second interface prototype, “E-EC Shuffle”, provides a more subjective view on the collection from “within” the material, complementary to the overview of the “Explorer”. Here, short clips from two randomly selected EC films play side by side, with films changing in alternating fashion after every few seconds. The selection is limited to films that fall under a Creative Commons license. This setup is meant to allow for a “sampling” of the large-scale collection to convey a sense of its filmic contents, aesthetics, and techniques, for instance. This parallel view also serves to test and hypothesize about possible projection situations that may have been historically intended for the presentation of EC films.

A further group of interfaces in the project each focuses on a particularly relevant subset or series of films, oriented along the three thematic sections of the collection: biology, technical sciences and ethnology. Here, selected films are arranged in compact overviews and capable to be played back simultaneously to allow for a concentrated comparative view. These interfaces are intended for a more detailed study of selected films that may exemplify the encyclopedic ambitions, aesthetic tendencies or historic conceptions of the EC as well as serve as visual arguments (in the sense of VSTS) to evaluate research hypotheses within the project.

The interfaces' overall aim is to also highlight the need for more context-specific research tools, especially when working with complex and rich-media materials like large film collections. They can show that the design of basic but tailored visual and organizational media operations (e.g. generating overview, filtering, selective and synchronous views) can already vastly open up and activate such materials for research and allow for more appropriate configurations that facilitate insights and argumentation.

Currently, the interfaces developed are mostly internal tools that help us sharpen research questions, develop designs, and deal with the restrictive legal issues surrounding the materials. During the development, we presented them to experts from various fields (such as science and museum studies) and adapted them according to their reactions. Further important steps in the evaluation process of the interfaces will be the feedback at the Digital History Conference and in the course of the art exhibition “String Figures / Fadenspiele. A Research Exhibition” at the Museum Tinguely Basel (November 2024 – March 2025),^[Curated by Mario Schulze and Sarine Waltenspül, see <https://www.tinguely.ch/en/exhibitions/exhibitions/2024/fadenspiele.html> (accessed 13/8/2024).] where some of the interfaces will be made accessible to the public. It is also planned to evaluate the more finalized versions of the interfaces outside the project, e.g. with people from the source communities, other EC experts, members of the TIB, or other researchers from large film collections.

**Team members**  
Moritz Greiner-Petter, Mario Schulze, Sarine Waltenspül
