---
submission_id: 460
categories: 'Session 3B'
title: 20 godparents and 3 wives – studying migrant glassworkers in post-medieval Estonia
author:
  - name: Monika Reppo
    orcid: 0000-0002-1643-7229
    email: monika.reppo@tlu.ee
    affiliations:
      - University of Tartu
funding:
  - statement: >
      The Project "Cooperation between universities to promote doctoral studies" (2021-2027.4.04.24-0003) is co-funded by the European Union.
keywords:
  - post-medieval archaeology
  - documentary archaeology
  - digitised records
abstract: |
  During my PhD research, ‘Glass and its makers in post-medieval Estonia’, genealogical data for 1,248 German-speaking migrant glassworkers and their family members from the 16th–19th century was collected. The data was compiled using church books and other relevant records indexed, digitised and/or transcribed by the National Archives of Estonia (NAE) and the Digital archive of Estonian newspapers (DEA) managed by the National Library of Estonia. NAE has recently begun employing and training Transkribus, an AI-powered platform in the text recognition and transcription of locally compiled historical documents. DEA uses Optical Character Recognition which enables users to search but also correct automatically created texts from newspapers. The data collected from these sources was tabulated and published on DataDOI, an Open Access repository managed by the University of Tartu library. This paper reflects on using these tools for large-scale data collection and the motivation behind publishing the raw data Open Access and the effects of it on my research. Using Gephi, an open-source visualisation program, the connections between individuals and locations in this dataset are presented to demonstrate how this data can be used in network analysis. The results offer a look into the lives of migrant glassworkers in the 17th–19th century in Estonia with a particular focus on godparents and godchildren and the connections within the glassworking community.
key-points:
  - This study explored the network of connections between 1,248 migrant glassworkers and their family members working in Estonia from the 16th-19th century, using Transkribus, OCR, and Gephi as the main tools.
  - The raw dataset was published via DataDOI, an Open Access repository managed by the University of Tartu library in accordance to FAIR principles.
  - The data shows that a key factor in building and maintaining the glass community was godparenting and marriages between the families.
date: 07-29-2024
bibliography: references.bib
---

## Introduction

As part of the author’s PhD project, ‘Glass and its makers in Estonia, c. 1550–1950: an archaeological study,’ the genealogical data about 1,248 migrant glassworkers and their family members working in Estonia from the 16th–19th century were collected using archival records and newspapers. The goal was to use information about key life events to trace the life histories of the glassworkers and their families from childhood to old age to gain an understanding of the community and the industry through one of its most important aspects – the workforce. It was hoped that the data will also assist in identifying the locations and names of glassworks during the period under study. In this paper, the author reflects on the process of this documentary archaeology research. The data collection, storage, and visualisation process are described, followed by the results of the study which have been included in a doctoral dissertation [@mythesis] and a research article [@reppo2023d].

## Data collection

The aim of this part of the PhD project was to collate, visualise, and publish data on the key life events of migrant glassworkers in post-medieval Estonia. Information on 1,248 individuals was obtained who are mostly of German origin. This list is in no way complete but provides information workers and their family members connected with the glass industry from the 16th century until the 1840s–1860s when the reliance on foreign workers started to lessen due to the abolishment of serfdom in Estonia which allowed locals access to skilled professions previously inaccessible to them [@mythesis, pp. 52].

The data were collected, tabulated, and made Open Access via DataDOI [@datadoi] as a raw dataset [@reppo2023b]. The following life events were considered – birth, baptism, marriage(s), and death. Both the date and place were included where possible to identify migration routes to and within Estonia. With baptisms, the number of godparents as well as names of all the godparents in the order listed in the church records were included. In total, the dataset has 1,249 rows and 22 columns. But how to find, access, and organise data about more than 1,200 individuals at this scale?

In addition to previously published sources and some additional archival information, this study mainly used records kept and digitised by the National Archives of Estonia (NAE) and the National Library of Estonia (NLE). During the period under study, the area of modern day Estonia was under the rule of the Swedish Kingdom (1561–1710) and the Russian Czardom (1710–1918). Due to the political history of the area, official business, including church records were kept in German well into the 19th century but also both Swedish and Russian during the respective periods. The newspapers considered in this study were also published in German and Russian as a result but there are also sources compiled in Estonian that were used in this study. This means the raw data could be in any of these languages.

As the dissertation and most of the articles connected to this thesis was written in English, all collected data was translated into English. For many of the entries on the dataset, the place name in the original source was in German. The currently used name is given first with the German version in brackets, for example, ‘Latvia, Suntaži (Sunzel).’ For Estonian place names, the German version is mostly not given but can be found in the Dictionary of Estonian Place Names (KNR; @knr). For the workers’ profession, the translated version is given first with the title from the original source, for example, ‘Hollow glass maker (Hohlgläser).’ For surnames, there is some change from German to Russian to Estonian and from church warden to another. The most common variations of a surname are given in brackets – for example, ‘Kilias (Kihlgas).’ This translation is not included for the glassworks as all used names and other details such as coordinates, operation dates, owners, and so on are given in another dataset [@reppo2023c].

## National Archives of Estonia

From the NAE, data were collected by identifying records using the Archival Information System [@ais], the name register for the Lutheran congregations [@luterikpn], and Saaga [@saaga]. With AIS and Saaga, it was possible to find references to records only available as paper copies at the NAE reading rooms in Tartu and Tallinn but also access digitised records, most of which were church books. NAE has estimated that around 34 million images of their physical records have been made available online which is roughly 5% of their collection [@rahvusarhiiv]. NAE adopted Transkribus, an AI-powered platform developed to transcribe and recognise historical handwritten documents and text in October 2022 [@ratranskribus] but a limited number of records are searchable through this feature at present.

Unfortunately, none of the records related to the glassworkers  life events under consideration in this study have been added yet. To test the employability of Transkribus as a non-expert user, a handful of 17th-century documents in Swedish were run through Transkribus [@transkribus] by the author to identify the location of a glassworks in Pärnu, Estonia. These records did not yield results that were hoped for but using Transkribus did speed up the process, even if the transcribed text needed corrections.

Despite the current lack of records related to the key life events of the glassworkers via the Transkribus engine on the NAE homepage, the archive has used family name indexes compiled in the 1960s–1980s at the present-day Estonian Ministry of the Interior’s IT and Development Centre Department of Population Services based on church books which were kept until the 1940s. Although many congregations have preserved church records already from the 18th century and some even from the 17th century, the church law legislated keeping church books only from 1834 onwards so the coverage varies across Estonia [@puss2024]. For this study, the focus was on the Kärevere-Laeva region which housed the largest number of Estonian glassworks from the mid-18th until the 20th century [@mythesis, pp. 35]. This means studying the church books from this area – Kursi and Kolga-Jaani parishes – was predicted to be the most advantageous exercise.

The indexes mentioned above are based on these records and list the last name with the relevant church book page numbers. Their digitisation was started in 2005 by the Estonian Association of Genealogists, taking advantage of researchers’ strong interest in this material [@puss2024]. Members and other volunteers thus digitised these indexes but also added their own indexes to this collection. The NAE complemented these surname indexes with a search engine which allows searching by date, parish, and last name. Over the years, the system has been developed to allow users to add image numbers which direct researchers to the correct image (page) in the digitised church book. Maiden names have also been partially indexed. The archive has now upscaled the use of this external help, crowdsourcing the indexing for specific thematic projects occasionally.

Although the crowdsourced indexes allowed identifying the records which included the glassworkers, and most of these were indeed digitised, the use of records from NAE during this study was certainly affected by the need to use traditional research methods to retrieve the information. Thus, thousands of pages of church books were combed through to compile the raw dataset after identifying the parishes with the highest number of glassworks. With further help from transcription services, the process of collecting basic data about key life events of the glassworkers and their family members could be streamlined further. Whilst some 17th-century records were uploaded to Transkribus for transcription to speed up the process of collecting very straightforward data for the individuals – dates and locations of key life events – future studies would certainly be facilitated by the built-in Transkribus engine on NAE.

## National Library of Estonia

Further information about the glassworkers and their family members was collected from the Digital archive of Estonian newspapers [@digar] which is managed by the NLE. As the newspapers available via this database were published from 1811 with some earlier exceptions. Unlike NAE, this collection employs Optical Character Recognition (OCR). The use of OCR for these records did significantly speed up the process of research. There were obviously errors, for example where OCR was unable to detect the layout of the text or where the print ink had bled. The database allows corrections from users. As the author of this study did correct the errors in recognised characters in the sources used for this study, future searches for other researchers should be less error-prone.

## Publication

Publication of raw datasets in Estonian archaeology is a new phenomenon and has been particularly rare for material culture studies which this study was a part of [@mythesis, pp. 38]. In addition to adhering to FAIR principles, the publication of this dataset is tied to an unusual situation – the author is the only archaeologists in Estonia studying post-medieval glass. In fact, three large datasets were published as part of this dissertation – one on archaeological finds [@reppo2023a], another on the workers [@reppo2023b], and a third one the glassworks themselves [@reppo2023c] to avoid research monopoly and encourage other researchers to study the post-medieval glass industry in Estonia.

The raw dataset was published Open Access under a CC-BY 4.0 licence via DataDOI, a free data repository which is managed by the University of Tartu library which provides the dataset with a persistent interoperable identifier. As mentioned above, the dataset of life events is tabulated and has 22 columns and 1,249 lines. It is accompanied by a metadata file which includes details on the project, the references, and other information relevant to the raw data.

## Visualisation

One of the goals of this study were to visualise the data to provide easily legible images (charts, models, drawings) which encompass the entirety of the collected data. The data were visualised using Gephi, an open-source visualisation program by extracting the raw data using pivot tables in Microsoft Excel and wrangling the data to remove unnecessary details and columns. This proved that the data is mutable and suitable for network analysis. For Gephi, this data needed to be sorted into nodes and edges which allows visualising the connections between several points of data by means of lines. After cleaning the data, the format was transformed from a Microsoft Excel table (.XLSX) to a .CSV file to run the model. In the model, the node (point) size is representative of the number of connections to the place or family. Glassworks are differentiated from birth, marriage, and death locations by the ‘GW’ (glassworks) in the name.

In this model, marriages between families and the connections of those families to places are plotted based on their places of origin, birth, baptism, marriage, and death. With further data wrangling it would be possible to show the connections of the glassworkers and their family members within the larger community beyond marriages by analysing the connections of those individuals who appear as godparents.

## Results

This study explored the network of connections between 1,248 migrant glassworkers and their family members working in Estonia from the 16th–19th century, using Transkribus, OCR, and Gephi as the main tools. A complete list of workers during this period was not the goal of this study. The raw dataset was published via DataDOI, an Open Access repository managed by the University of Tartu library in accordance to FAIR principles. The data shows that a key factor in building and maintaining the glass community was godparenting and marriages between the families. In addition to tracing migration to, within, and from Estonia, the data also allowed identifying the makers of some archaeological glass artefacts and locations and names of glassworks.

::: {.callout-note}
The Project "Cooperation between universities to promote doctoral studies" (2021-2027.4.04.24-0003) is co-funded by the European Union.
:::

## References

::: {#refs}
:::
